// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ3g-5oFz7GYH4BSyiuhG30aw3KfdDzSs',
    appId: '1:1085806519394:web:ee09bf4349693d6f1c9d3b',
    messagingSenderId: '1085806519394',
    projectId: 'minimal-social-app-22508',
    authDomain: 'minimal-social-app-22508.firebaseapp.com',
    storageBucket: 'minimal-social-app-22508.appspot.com',
    measurementId: 'G-Q0ZQX30M10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuEvAQDgD-FH1usjaoM24TG9Q8kbjxQ5I',
    appId: '1:1085806519394:android:2a21dbf7ca1f20ad1c9d3b',
    messagingSenderId: '1085806519394',
    projectId: 'minimal-social-app-22508',
    storageBucket: 'minimal-social-app-22508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlWEQPlqgJ1sSBqf6_gNoBFog6d8kUCY8',
    appId: '1:1085806519394:ios:b1ff8010d0ae20351c9d3b',
    messagingSenderId: '1085806519394',
    projectId: 'minimal-social-app-22508',
    storageBucket: 'minimal-social-app-22508.appspot.com',
    iosBundleId: 'com.example.noor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlWEQPlqgJ1sSBqf6_gNoBFog6d8kUCY8',
    appId: '1:1085806519394:ios:339d419a722044bf1c9d3b',
    messagingSenderId: '1085806519394',
    projectId: 'minimal-social-app-22508',
    storageBucket: 'minimal-social-app-22508.appspot.com',
    iosBundleId: 'com.example.noor.RunnerTests',
  );
}
